In [1]:
import numpy as np

In [2]:
mylist = [1.,2.,4.,5.,6.]

In [3]:
mynparray = np.array(mylist)

In [4]:
mynparray

array([1., 2., 4., 5., 6.])

In [5]:
one_vector = np.ones(4)

In [6]:
one_vector

array([1., 1., 1., 1.])

In [7]:
one_vector = np.zeros(4)

In [9]:
one_vector
print(one_vector)

[0. 0. 0. 0.]


In [11]:
one2Darray = np.ones((2,4))
print(one2Darray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
empty_vector = np.empty(1)
print(empty_vector)

[4.6798694e-310 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]


In [19]:
mynparray[2]

4.0

In [23]:
my_matrix = np.array([[1,2,3],[4,5,6]])
print(my_matrix)

[[1 2 3]
 [4 5 6]]


In [26]:
print(my_matrix[1,0])

4


In [27]:
print (my_matrix[0:2, 2]) # recall 0:2 = [0, 1]

[3 6]


In [29]:
print(my_matrix[0,0:3])

[1 2 3]


In [32]:
fib_indices = np.array([1, 1, 2, 3])
random_vector = np.random.random(10) # 10 random numbers between 0 and 1
print (random_vector)

[0.82345402 0.95360966 0.75421812 0.01669674 0.02528563 0.23337574
 0.68300078 0.88041144 0.61371813 0.32451776]


In [33]:
print (random_vector[fib_indices])


[0.95360966 0.95360966 0.75421812 0.01669674]


In [35]:
my_vector = np.array([1, 2, 3, 4])
select_index = np.array([True, False, True, True])
print (my_vector[select_index])

[1 3 4]


In [36]:
select_cols = np.array([True, False, True]) # 1st and 3rd column
select_rows = np.array([False, True]) # 2nd row

In [37]:
print (my_matrix[select_rows, :]) # just 2nd row but all columns

[[4 5 6]]


In [39]:
print (my_matrix[:, select_cols]) # all rows and just the 1st and 3rd column

[[1 3]
 [4 6]]


In [40]:
my_array = np.array([1., 2., 3., 4.])
print (my_array*my_array)

[ 1.  4.  9. 16.]


In [43]:
print (my_array**2)

[ 1.  4.  9. 16.]


In [44]:
print (my_array*2)

[2. 4. 6. 8.]


In [45]:
print (my_array - np.ones(4))

[0. 1. 2. 3.]


In [46]:
print (my_array / 3)

[0.33333333 0.66666667 1.         1.33333333]


In [47]:
print (my_array / np.array([2., 3., 4., 5.]) )# = [1.0/2.0, 2.0/3.0, 3.0/4.0, 4.0/5.0]

[0.5        0.66666667 0.75       0.8       ]


In [48]:
print (np.sum(my_array))

10.0


In [49]:
print (np.average(my_array))

2.5


In [50]:
print (np.sum(my_array)/len(my_array))

2.5
